services:
  #SQL Express Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P4ssw0rd
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      # These are in appsettings.Development.json for development
      #- "Todo__ConnectionStringPostgres=Host=127.0.0.1;Port=5432;Username=user;Password=password;Database=db"
      #- "Todo__ConnectionStringMssql=Data Source=127.0.0.1,1433;User=sa;Password=P4ssw0rd;Encrypt=no;"
    ports:
      - "80:80"